//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHang.Model
{
    using System;
    using System.Collections.Generic;
    using QuanLyCuaHang.ViewModel;
    
    public partial class HDB:BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HDB()
        {
            this.TTHDBs = new HashSet<TTHDB>();
        }

        private string id;
        private string idNV;
        private string idKH;
        public string Id { get => id; set { id = value; OnPropertyChanged(); } }
        public string IdNV { get => idNV; set { idNV = value; OnPropertyChanged(); } }
        public string IdKH { get => idKH; set { idKH = value; OnPropertyChanged(); } }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public Nullable<double> TongTien { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTHDB> TTHDBs { get; set; }

    }
}
