//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHang.Model
{
    using QuanLyCuaHang.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiTK : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiTK()
        {
            this.TaiKhoans = new HashSet<TaiKhoan>();
        }

        private int id;
        private string tenLoaiTK;
        public int Id { get => id; set { id = value; OnPropertyChanged(); } }
        public string TenLoaiTK { get => tenLoaiTK; set { tenLoaiTK = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
        
    }
}
