//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHang.Model
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media.Imaging;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.TTHDBs = new HashSet<TTHDB>();
            this.TTHDNs = new HashSet<TTHDN>();
        }
    
        public string Id { get; set; }
        public string Anh { get; set; }
        public string TenSP { get; set; }
        public int IdLoaiSP { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public string GhiChu { get; set; }
        private BitmapImage _Url;
        public BitmapImage Url { get => _Url; set => _Url = value; }

        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual TonKho TonKho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTHDB> TTHDBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTHDN> TTHDNs { get; set; }
    }
}
