//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Size
    {
        public int Id { get; set; }
        public int IdLSP { get; set; }
        public string KichThuoc { get; set; }
    
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual TTNhapSP TTNhapSP { get; set; }
    }
}
