//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHang.Model
{
    using System;
    using System.Collections.Generic;
    using QuanLyCuaHang.ViewModel;

    public partial class TaiKhoan:BaseViewModel
    {
        private int id;
        private string idNV;
        private string username;
        private string password;
        private int idLoaiTK;

        public virtual LoaiTK LoaiTK { get; set; }
        public virtual NhanVien NhanVien { get; set; }

        public int Id { get => id; set { id = value; OnPropertyChanged(); } }
        public string IdNV { get => idNV; set { idNV = value; OnPropertyChanged(); } }
        public string Username { get => username; set { username = value; OnPropertyChanged(); } }
        public string Password { get => password; set { password = value; OnPropertyChanged(); } }
        public int IdLoaiTK { get => idLoaiTK; set { idLoaiTK = value; OnPropertyChanged(); } }
    }
}
