//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHang.Model
{
    using System;
    using System.Collections.Generic;
    using QuanLyCuaHang.ViewModel;

    public partial class TTHDN:BaseViewModel
    {
        private string id;
        private string idSP;
        private int idNCC;
        private int idSize;
        private string idHDN;
        private Nullable<double> giaNhap;
        private Nullable<int> sLNhap;

        public virtual HDN HDN { get; set; }
        public virtual NCC NCC { get; set; }
        public virtual SanPham SanPham { get; set; }
        public virtual Size Size { get; set; }

        public string Id { get => id; set { id = value; OnPropertyChanged(); } }
        public string IdSP { get => idSP; set { idSP = value; OnPropertyChanged(); } }
        public int IdNCC { get => idNCC; set { idNCC = value; OnPropertyChanged(); } }
        public int IdSize { get => idSize; set { idSize = value; OnPropertyChanged(); } }
        public string IdHDN { get => idHDN; set { idHDN = value; OnPropertyChanged(); } }
        public double? GiaNhap { get => giaNhap; set { giaNhap = value; OnPropertyChanged(); } }
        public int? SLNhap { get => sLNhap; set { sLNhap = value; OnPropertyChanged(); } }
    }
}
