//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTNhapSP
    {
        public int IdSize { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public Nullable<int> SLNhap { get; set; }
    
        public virtual Size Size { get; set; }
    }
}
